CREATE SEQUENCE USER_ID_SEQ;

DROP TABLE users cascade constraints;

CREATE TABLE USERS
( USER_ID     NUMBER(6) PRIMARY KEY NOT NULL,
  LOGIN_NAME  VARCHAR2(50),
  FIRST_NAME      VARCHAR2(20),
  LAST_NAME       VARCHAR2(25) ,
  PHOTO_ID        NUMBER(6),
  EMAIL           VARCHAR2(50) CONSTRAINT USER_EMAIL_NN NOT NULL,
  CREATED_DATE    DATE CONSTRAINT USER_CREATED_DATE_NN NOT NULL,
  RETIREE         varchar2(1) DEFAULT 'N',
  HORSE_POWER     NUMBER(6)
);
  
ALTER TABLE USERS ADD (
  CONSTRAINT USERS_EMAIL_UK
 UNIQUE (EMAIL)
    USING INDEX) ;
    
CREATE SEQUENCE PROFILE_ID_SEQ;  

DROP TABLE PROFILE CASCADE CONSTRAINTS;
CREATE TABLE PROFILES
( PROFILE_ID NUMBER(6) PRIMARY KEY NOT NULL,
  USER_ID     NUMBER(6) 
);

ALTER TABLE PROFILES ADD (
  CONSTRAINT PROFILES_USER_ID_FK 
 FOREIGN KEY (USER_ID) 
 REFERENCES USERS (USER_ID));
 
CREATE SEQUENCE STORY_ID_SEQ; 

DROP TABLE stories CASCADE CONSTRAINTS;
CREATE TABLE STORIES
( STORY_ID     NUMBER(10) PRIMARY KEY NOT NULL,
  STORY_TITLE  VARCHAR2(300),
  STORY_URL  VARCHAR2(300),
  STORY_TEASER  VARCHAR2(300),
  STORY_CREATED_DATE    DATE CONSTRAINT STORY_CREATED_DATE NOT NULL,
  POSTED_BY_USER_ID     NUMBER(6),
  PHOTO_ID  NUMBER(8),
  VIDEO_ID  NUMBER(8),
  VOTES NUMBER(6)
);

ALTER TABLE STORIES ADD (
  CONSTRAINT STORIES_STORIES_ID_FK 
 FOREIGN KEY (POSTED_BY_USER_ID) 
 REFERENCES USERS (USER_ID));
 
 CREATE SEQUENCE COMMENT_ID_SEQ; 
 
 DROP TABLE comments CASCADE CONSTRAINTS; 
 CREATE TABLE COMMENTS
( COMMENT_ID NUMBER(10) PRIMARY KEY NOT NULL,
  STORY_ID  NUMBER(10),
  COMMENT_TEXT VARCHAR2(140),
  COMMENTED_BY_USER_ID NUMBER(6) CONSTRAINT COMMENTED_BY_USER_ID NOT NULL,
  COMMENT_CREATED_DATE DATE CONSTRAINT COMMENT_CREATED_DATE NOT NULL,
  COMMENT_MODERATED VARCHAR2(1) DEFAULT 'N'  
);

ALTER TABLE COMMENTS ADD (
  CONSTRAINT COMMENTS_STORY_ID_FK 
 FOREIGN KEY (STORY_ID) 
 REFERENCES STORIES (STORY_ID));
 
 CREATE SEQUENCE PHOTO_ID_seq;
 
 DROP TABLE photos CASCADE CONSTRAINTS;
 CREATE TABLE PHOTOS
( PHOTO_ID NUMBER(10) PRIMARY KEY NOT NULL,
  USER_ID NUMBER(6),
  STORY_ID  NUMBER(10),
  PHOTO_FILE_NAME VARCHAR2(140),
  PHOTO_FILE_PATH VARCHAR2(140)
);

ALTER TABLE PHOTOS ADD (
  CONSTRAINT PHOTOS_STORY_ID_FK 
 FOREIGN KEY (STORY_ID) 
 REFERENCES STORIES (STORY_ID));
 
 ALTER TABLE PHOTOS ADD (
  CONSTRAINT PHOTOS_USER_ID_FK 
 FOREIGN KEY (USER_ID) 
 REFERENCES USERS (USER_ID));
 
 CREATE SEQUENCE video_id_seq;
 
 DROP TABLE VIDEOS CASCADE CONSTRAINTS;
 CREATE TABLE VIDEOS
( VIDEO_ID NUMBER(10) PRIMARY KEY NOT NULL,
  USER_ID NUMBER(6),
  STORY_ID  NUMBER(10),
  VIDEO_FILE_NAME VARCHAR2(140),
  VIDEO_FILE_PATH VARCHAR2(140)
);

ALTER TABLE VIDEOS ADD (
  CONSTRAINT VIDEO_STORY_ID_FK 
 FOREIGN KEY (STORY_ID) 
 REFERENCES STORIES (STORY_ID));
 
 ALTER TABLE VIDEOS ADD (
  CONSTRAINT VIDEO_USER_ID_FK 
 FOREIGN KEY (USER_ID) 
 REFERENCES USERS (USER_ID));
 
 CREATE SEQUENCE FRIEND_ID_SEQ;
 
  DROP TABLE FRIENDS CASCADE CONSTRAINTS;
 CREATE TABLE FRIENDS
( FRIEND_ID NUMBER(6) PRIMARY KEY NOT NULL,
  USER_ID NUMBER(6),
  FRIENDING_USER_ID  NUMBER(6)
);

ALTER TABLE FRIENDS ADD (
  CONSTRAINT FRIENDS_USER_ID_FK 
 FOREIGN KEY (USER_ID) 
 REFERENCES USERS (USER_ID));
 
 ALTER TABLE FRIENDS ADD (
  CONSTRAINT FRIENDS_FRIENDING_USER_ID_FK 
 FOREIGN KEY (FRIENDING_USER_ID) 
 REFERENCES USERS (USER_ID));
 
 
create or replace view news_page_stories_vw as
   select stories.STORY_TITLE, stories.STORY_URL, stories.STORY_TEASER,
       comments.COMMENT_TEXT, comments.COMMENT_CREATED_DATE, users.LOGIN_NAME
   from
       stories, comments, users
   where
      stories.STORY_ID = comments.STORY_ID and
      comments.COMMENTED_BY_USER_ID = users.USER_ID
   order by comments.COMMENT_CREATED_DATE DESC;
 
 
 







